var m = 100;
var fname = "Raj";
var result1 = true;
var msg = 200;
msg = "Ajay";
msg = true;
//m = "Ravi";
var n = 200;
var lname = "Deep";
var result2 = false;
var id;
var fullname;
var result;
id = 200;
fullname = "Ram Patil";
result = true;
console.log(id);
console.log(fullname);
console.log(fullname);
